import { scoreSighting, emptySighting } from "@/lib/score";
import type { IncomingPost, Sighting } from "@/lib/types";

function chart(ticker: string) {
  return `/api/chart/${ticker.toUpperCase()}`;
}

function row(partial: Partial<Sighting>): Sighting {
  return emptySighting({
    hasDaily: true,
    hasWeekly: true,
    hasFivePanelChart: true,
    accelPrice: "148",
    invPrice: "142",
    zoneLow: "142",
    zoneHigh: "150",
    ...partial,
    chartImage: partial.chartImage ?? chart(partial.ticker ?? "x"),
  });
}

const sightings: Sighting[] = [
  row({
    ticker: "AVGO",
    name: "Broadcom",
    ribbon: "red_widening",
    candle: "fresh_red_wm",
    redAgeDays: 1,
    whalePct: 82,
    whaleRising: true,
    atSupport: true,
    chip: "above_support",
    panel2: "flip_green_red_widening",
    accelPrice: "172",
    invPrice: "164",
    zoneLow: "164",
    zoneHigh: "172",
    closePrice: "166",
    notes: "Rossa weekly fresca, ribbon che si allarga, whale alti, close ancora sulla zona.",
  }),
  row({
    ticker: "NVDA",
    name: "NVIDIA",
    ribbon: "red_widening",
    candle: "fresh_red_wm",
    redAgeDays: 2,
    whalePct: 82,
    whaleRising: true,
    chaseClose: true,
    closePrice: "154",
    zoneLow: "142",
    zoneHigh: "150",
    accelPrice: "150",
    invPrice: "142",
    notes: "Canone: ribbon rossa, whale 82%, rossa W, close 154 chase. Il voto resta alto, non è Buy.",
  }),
  row({
    ticker: "AAPL",
    name: "Apple",
    ribbon: "red_widening",
    candle: "fresh_red_wm",
    redAgeDays: 3,
    whalePct: 68,
    whaleRising: true,
    atSupport: true,
    chip: "flipped_res_to_sup",
    accelPrice: "218",
    invPrice: "209",
    zoneLow: "209",
    zoneHigh: "218",
    closePrice: "211",
    notes: "Struttura ok, whale sotto 75: Buy sulla zona, non Strong Buy.",
  }),
  row({
    ticker: "AMD",
    name: "AMD",
    ribbon: "red_widening",
    candle: "dark_blue_continuation",
    whalePct: 71,
    whaleRising: true,
    atSupport: true,
    chip: "above_support",
    accelPrice: "164",
    invPrice: "156",
    zoneLow: "156",
    zoneHigh: "164",
    closePrice: "158",
    notes: "Blu di continuazione su ribbon rossa. Buy se resta in zona.",
  }),
  row({
    ticker: "TSLA",
    name: "Tesla",
    candle: "yellow_weekly",
    ribbon: "red_widening",
    whalePct: 77,
    whaleRising: true,
    atSupport: true,
    accelPrice: "248",
    invPrice: "232",
    zoneLow: "232",
    zoneHigh: "248",
    notes: "Gialla weekly: tetto 5, Hold, nessuna zona da comprare adesso.",
  }),
  row({
    ticker: "META",
    name: "Meta",
    hole: "early_with_blue",
    ribbon: "thick_blue_above",
    whalePct: 58,
    whaleRising: true,
    accelPrice: "512",
    invPrice: "488",
    zoneLow: "488",
    zoneHigh: "512",
    notes: "Hole + blu discendente: prima accumulazione, non è buy pieno.",
  }),
  row({
    ticker: "AMZN",
    name: "Amazon",
    hasWeekly: false,
    hasMonthly: false,
    ribbon: "red_widening",
    candle: "fresh_red_wm",
    redAgeDays: 1,
    whalePct: 74,
    whaleRising: true,
    atSupport: true,
    notes: "Manca il weekly: tetto 5, un 8 qui non esiste.",
  }),
  row({
    ticker: "PLTR",
    name: "Palantir",
    ribbon: "red_thinning",
    candle: "fresh_red_wm",
    redAgeDays: 8,
    whalePct: 44,
    whaleDeclining: true,
    accelPrice: "38",
    invPrice: "34",
    zoneLow: "34",
    zoneHigh: "38",
    notes: "Ribbon che si stringe, whale sotto 50 in calo.",
  }),
  row({
    ticker: "NFLX",
    name: "Netflix",
    ribbon: "red_widening",
    candle: "fresh_red_wm",
    whalePct: 28,
    atSupport: true,
    notes: "Whale sotto 35: tetto 4.",
  }),
  row({
    ticker: "GOOGL",
    name: "Alphabet",
    ribbon: "thick_blue_above",
    candle: "dark_blue_continuation",
    whalePct: 51,
    whaleRising: true,
    accelPrice: "168",
    invPrice: "159",
    notes: "Blu spessa sopra il prezzo: tetto 3, non è un buy.",
  }),
  row({
    ticker: "COIN",
    name: "Coinbase",
    hole: "close_below_low",
    ribbon: "red_widening",
    whalePct: 61,
    whaleRising: true,
    notes: "Hole bucato in giù: ramo sell, non si somma.",
  }),
  row({
    ticker: "SMCI",
    name: "Super Micro",
    candle: "yellow_monthly",
    whaleDeclining: true,
    dailyLooksGood: true,
    ribbon: "red_widening",
    whalePct: 39,
    notes: "Monthly rotto mentre il daily è bello: Sell Now.",
  }),
];

export const seedPosts: IncomingPost[] = [
  {
    id: "post-must-1",
    source: "patreon",
    kind: "must_read",
    title: "MUST READ — AVGO weekly rossa, zona 164-172",
    body: "AVGO ha aperto la weekly rossa sulla ribbon. Whale alti. Due prezzi scritti: accel 172, inv 164. Non è un nome, è un setup da buy sulla zona.",
    ticker: "AVGO",
    imageUrl: chart("AVGO"),
    receivedAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    routedTo: ["analyst", "sender"],
  },
  {
    id: "post-buy-1",
    source: "patreon",
    kind: "my_buy",
    title: "My BUY — AAPL close ancora in zona",
    body: "AAPL: ribbon rossa, CHIP appena girato da resistenza a supporto. Close 211, zona 209-218. Whale 68% in salita.",
    ticker: "AAPL",
    imageUrl: chart("AAPL"),
    receivedAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    routedTo: ["analyst", "sender"],
  },
  {
    id: "post-bull-1",
    source: "mail",
    kind: "bullish",
    title: "Bullish Signals — AMD continuazione blu su rossa",
    body: "AMD tiene la ribbon. Blu scure di continuazione. Non inseguire il close se esce dalla zona 156-164.",
    ticker: "AMD",
    imageUrl: chart("AMD"),
    receivedAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    routedTo: ["analyst", "sender"],
  },
  {
    id: "post-trend-1",
    source: "patreon",
    kind: "trending",
    title: "Trending — NVDA close 154, zona 142-150",
    body: "NVDA ribbon rossa e whale 82%, ma il close è già 154. Chase. Il 7 vale sulla zona, non su questo close.",
    ticker: "NVDA",
    imageUrl: chart("NVDA"),
    receivedAt: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    routedTo: ["analyst", "sender"],
  },
  {
    id: "post-how-1",
    source: "patreon",
    kind: "how_to",
    title: "HOW TO — come si vota il setup, non il nome",
    body: "Parte da 0, si somma, poi si taglia con i tetti. Ogni punto deve essere visibile sul grafico. Se non c’è il pezzo, quel punto non si dà. Senza weekly il voto non può superare 5. Whale sotto 50: niente Buy da carrello. Il carrello ogni 4 ore arriva solo al CEO. Non si tocca wallet, non si fa size, non si scrive su Telegram dall’Analyst.",
    ticker: null,
    imageUrl: null,
    receivedAt: new Date(Date.now() - 80 * 60 * 1000).toISOString(),
    routedTo: ["ceo"],
  },
  {
    id: "post-other-1",
    source: "mail",
    kind: "other",
    title: "Note di mercato — SMCI monthly gialla",
    body: "SMCI: daily ancora pulito, monthly gialla e whale in calo. Non sommare. Ramo sell.",
    ticker: "SMCI",
    imageUrl: chart("SMCI"),
    receivedAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    routedTo: ["analyst"],
  },
];

export function seedAnalyses() {
  const now = Date.now();
  return sightings.map((sighting, index) => ({
    id: `an-${sighting.ticker.toLowerCase()}`,
    sighting,
    score: scoreSighting(sighting),
    updatedAt: new Date(now - index * 60_000).toISOString(),
  }));
}
